/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ResidencyManagement;

import com.mongodb.MongoClient;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author Sandesh
 */
public class Announcement extends javax.swing.JFrame {

    /**
     * Creates new form Issues
     */
    String username;
    public Announcement() {
        initComponents();
        pnlAnnouncement.removeAll();
        pnlAnnouncement.revalidate();
        this.getContentPane().setBackground(new Color(72,209,204));
    }
    public Announcement(String username) {
        initComponents();
        pnlAnnouncement.removeAll();
        pnlAnnouncement.revalidate();
        this.username=username;
        this.getContentPane().setBackground(new Color(72,209,204));
    }
    public void infoMessage(String message,String title)
    {
        JOptionPane.showMessageDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnShowIssue = new javax.swing.JButton();
        btnCreateIssue = new javax.swing.JButton();
        pnlAnnouncement = new javax.swing.JLayeredPane();
        pnlShowIssue1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblShowAnn = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnDeleteAnn = new javax.swing.JButton();
        pnlCreateIssue1 = new javax.swing.JPanel();
        lblCreateIssuesIssueType1 = new javax.swing.JLabel();
        lblCreateIssuesApartmentName1 = new javax.swing.JLabel();
        txtWing = new javax.swing.JTextField();
        lblCreateIssuesDescription1 = new javax.swing.JLabel();
        btnCreateIssuesSubmit1 = new javax.swing.JButton();
        btnAnnouncementSubmit2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        txtTopic = new javax.swing.JTextField();
        btnBackAdminAnnouncement = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(72, 209, 204));

        btnShowIssue.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnShowIssue.setText("View Announcements");
        btnShowIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowIssueActionPerformed(evt);
            }
        });

        btnCreateIssue.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnCreateIssue.setText("Give Announcement");
        btnCreateIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateIssueActionPerformed(evt);
            }
        });

        pnlAnnouncement.setBackground(new java.awt.Color(72, 209, 204));

        pnlShowIssue1.setBackground(new java.awt.Color(72, 209, 204));
        pnlShowIssue1.setAutoscrolls(true);
        pnlShowIssue1.setPreferredSize(new java.awt.Dimension(1370, 800));

        tblShowAnn.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tblShowAnn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ann Id", "Date", "Topic", "Wing(s)", "Announcement"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblShowAnn.setRequestFocusEnabled(false);
        tblShowAnn.setRowHeight(30);
        jScrollPane5.setViewportView(tblShowAnn);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 18)); // NOI18N
        jLabel4.setText("Delete Announcement");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel5.setText("ID");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        btnDeleteAnn.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        btnDeleteAnn.setText("Delete");
        btnDeleteAnn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAnnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlShowIssue1Layout = new javax.swing.GroupLayout(pnlShowIssue1);
        pnlShowIssue1.setLayout(pnlShowIssue1Layout);
        pnlShowIssue1Layout.setHorizontalGroup(
            pnlShowIssue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowIssue1Layout.createSequentialGroup()
                .addGap(257, 257, 257)
                .addGroup(pnlShowIssue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlShowIssue1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 677, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1012, 1012, 1012))
                    .addGroup(pnlShowIssue1Layout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(btnDeleteAnn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlShowIssue1Layout.createSequentialGroup()
                .addGap(525, 525, 525)
                .addComponent(jLabel4)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlShowIssue1Layout.setVerticalGroup(
            pnlShowIssue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowIssue1Layout.createSequentialGroup()
                .addGroup(pnlShowIssue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlShowIssue1Layout.createSequentialGroup()
                        .addGroup(pnlShowIssue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlShowIssue1Layout.createSequentialGroup()
                                .addGap(386, 386, 386)
                                .addComponent(jLabel3)
                                .addGap(0, 0, 0)
                                .addComponent(jLabel2))
                            .addGroup(pnlShowIssue1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel4)
                        .addGap(21, 21, 21)
                        .addGroup(pnlShowIssue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnDeleteAnn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(262, 262, 262))
        );

        pnlCreateIssue1.setBackground(new java.awt.Color(72, 209, 204));
        pnlCreateIssue1.setPreferredSize(new java.awt.Dimension(1370, 800));

        lblCreateIssuesIssueType1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblCreateIssuesIssueType1.setText("Topic");

        lblCreateIssuesApartmentName1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblCreateIssuesApartmentName1.setText("Wing Name");

        txtWing.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtWing.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWingActionPerformed(evt);
            }
        });

        lblCreateIssuesDescription1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblCreateIssuesDescription1.setText("Description");

        btnCreateIssuesSubmit1.setText("Submit");
        btnCreateIssuesSubmit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateIssuesSubmit1ActionPerformed(evt);
            }
        });

        btnAnnouncementSubmit2.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        btnAnnouncementSubmit2.setText("Submit");
        btnAnnouncementSubmit2.setToolTipText("");
        btnAnnouncementSubmit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnnouncementSubmit2ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        txtTopic.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtTopic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTopicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlCreateIssue1Layout = new javax.swing.GroupLayout(pnlCreateIssue1);
        pnlCreateIssue1.setLayout(pnlCreateIssue1Layout);
        pnlCreateIssue1Layout.setHorizontalGroup(
            pnlCreateIssue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateIssue1Layout.createSequentialGroup()
                .addGroup(pnlCreateIssue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreateIssue1Layout.createSequentialGroup()
                        .addGap(660, 660, 660)
                        .addComponent(btnCreateIssuesSubmit1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCreateIssue1Layout.createSequentialGroup()
                        .addGap(306, 306, 306)
                        .addGroup(pnlCreateIssue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblCreateIssuesApartmentName1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreateIssuesIssueType1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCreateIssuesDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(pnlCreateIssue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtTopic, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(txtWing, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)))
                    .addGroup(pnlCreateIssue1Layout.createSequentialGroup()
                        .addGap(482, 482, 482)
                        .addComponent(btnAnnouncementSubmit2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlCreateIssue1Layout.setVerticalGroup(
            pnlCreateIssue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateIssue1Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(pnlCreateIssue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateIssuesIssueType1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTopic, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(pnlCreateIssue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateIssuesApartmentName1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtWing, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addGroup(pnlCreateIssue1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCreateIssuesDescription1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(btnAnnouncementSubmit2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297)
                .addComponent(btnCreateIssuesSubmit1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlAnnouncement.setLayer(pnlShowIssue1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlAnnouncement.setLayer(pnlCreateIssue1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlAnnouncementLayout = new javax.swing.GroupLayout(pnlAnnouncement);
        pnlAnnouncement.setLayout(pnlAnnouncementLayout);
        pnlAnnouncementLayout.setHorizontalGroup(
            pnlAnnouncementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(pnlAnnouncementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAnnouncementLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(pnlShowIssue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(pnlAnnouncementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAnnouncementLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(pnlCreateIssue1, javax.swing.GroupLayout.PREFERRED_SIZE, 1291, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(91, Short.MAX_VALUE)))
        );
        pnlAnnouncementLayout.setVerticalGroup(
            pnlAnnouncementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 820, Short.MAX_VALUE)
            .addGroup(pnlAnnouncementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAnnouncementLayout.createSequentialGroup()
                    .addGap(5, 5, 5)
                    .addComponent(pnlShowIssue1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(pnlAnnouncementLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAnnouncementLayout.createSequentialGroup()
                    .addGap(7, 7, 7)
                    .addComponent(pnlCreateIssue1, javax.swing.GroupLayout.PREFERRED_SIZE, 781, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(32, Short.MAX_VALUE)))
        );

        btnBackAdminAnnouncement.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnBackAdminAnnouncement.setText("< Back");
        btnBackAdminAnnouncement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackAdminAnnouncementActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnBackAdminAnnouncement, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnCreateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnShowIssue)))
                .addGap(36, 36, 36)
                .addComponent(pnlAnnouncement, javax.swing.GroupLayout.PREFERRED_SIZE, 1249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBackAdminAnnouncement)
                        .addGap(40, 40, 40)
                        .addComponent(btnCreateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(btnShowIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlAnnouncement, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(110, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowIssueActionPerformed
        // TODO add your handling code here:
        pnlAnnouncement.removeAll();
        pnlAnnouncement.revalidate();
        pnlAnnouncement.add(pnlShowIssue1);
        pnlAnnouncement.revalidate();
        
        String ColumnName[] = {"Ann ID" ,"Date", "Topic", "Wing(s)", "Announcement"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(ColumnName);
        tblShowAnn.setModel(model);
        try{
            try (MongoClient mongo = new MongoClient( "localhost" , 27017 )) {
                MongoDatabase db = mongo.getDatabase("RESIDEM");
                //db.createCollection("AnnouncementsDB");
                MongoCollection<Document> AnnouncementsDB = db.getCollection("AnnouncementsDB");
                
                FindIterable<Document> iterable =  AnnouncementsDB.find ();
                MongoCursor<Document> cursor = iterable.iterator();
                while(cursor.hasNext()){
                    Document entry = cursor.next();
                    model.addRow( new Object[]{ entry.get("annid"), entry.get("date"), entry.get("topic"), entry.get("wing"), entry.get("announcement") });
                }
            }
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnShowIssueActionPerformed

    private void btnCreateIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateIssueActionPerformed
        // TODO add your handling code here:
        pnlAnnouncement.removeAll();
        pnlAnnouncement.revalidate();
        pnlAnnouncement.add(pnlCreateIssue1);
        pnlAnnouncement.revalidate();
        
    }//GEN-LAST:event_btnCreateIssueActionPerformed

    private void txtWingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWingActionPerformed

    private void btnCreateIssuesSubmit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateIssuesSubmit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateIssuesSubmit1ActionPerformed

    private void btnAnnouncementSubmit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnnouncementSubmit2ActionPerformed
        // TODO add your handling code here:
        String Wing = txtWing.getText();
        String Topic = txtTopic.getText();
        String Announcement = jTextArea1.getText();
        try{
            MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
             MongoDatabase db = mongo.getDatabase("RESIDEM");
             //db.createCollection("AnnouncementsDB");
             MongoCollection<Document> AnnouncementsDB = db.getCollection("AnnouncementsDB");
             DateFormat df = new SimpleDateFormat("dd/MM/yy HH:mm:ss");
            Date dateobj = new Date();
//            System.out.println(df.format(dateobj));
            String postDate = df.format(dateobj);
            int generatedAnnID;
            while(true){
                    Random rand = new Random();
                    generatedAnnID = rand.nextInt(100000); 
                    FindIterable<Document> iterable =  AnnouncementsDB.find ( Filters.eq("annid", generatedAnnID) );
                    MongoCursor<Document> cursor = iterable.iterator();
                    if(!(cursor.hasNext())){
                        break;
                    }
           }
            
            AnnouncementsDB.insertOne(new Document("annid" , generatedAnnID).append("date", postDate).append("topic", Topic).append("wing", Wing).append("announcement", Announcement));
            //txtCreateIssuesFirstName.setText("");
            //jTextArea2.setText("");
            this.dispose();
            new Announcement(username).setVisible(true);
             infoMessage("Announcement #" + generatedAnnID   + " Added!", "Announcement Posted Successfully!");
                  
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnAnnouncementSubmit2ActionPerformed

    private void txtTopicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTopicActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTopicActionPerformed

    private void btnDeleteAnnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAnnActionPerformed
        // TODO add your handling code here:
        String s=jTextField1.getText();
        int id=Integer.parseInt(s);
        try{
            MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
             MongoDatabase db = mongo.getDatabase("RESIDEM");
             //db.createCollection("IssuesDB");
             MongoCollection<Document> AnnouncementsDB = db.getCollection("AnnouncementsDB");
             
                    FindIterable<Document> iterable =  AnnouncementsDB.find (Filters.eq("annid",id));
                    MongoCursor<Document> cursor = iterable.iterator();
                    if(cursor.hasNext()){
                        AnnouncementsDB.deleteOne(Filters.eq("annid",id));
                        infoMessage("Announcement #"+id+" deleted!","Success");
                        this.dispose();
                        new Announcement(username).setVisible(true);
                    }
                    else
                    {
                        infoMessage("Announcement #"+id+" Not Found!","Failure");
                    }
                   
                  //mongo.close();
                   
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnDeleteAnnActionPerformed

    private void btnBackAdminAnnouncementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackAdminAnnouncementActionPerformed
        // TODO add your handling code here:
        new com.Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackAdminAnnouncementActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Announcement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Announcement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Announcement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Announcement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Announcement().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnnouncementSubmit2;
    private javax.swing.JButton btnBackAdminAnnouncement;
    private javax.swing.JButton btnCreateIssue;
    private javax.swing.JButton btnCreateIssuesSubmit1;
    private javax.swing.JButton btnDeleteAnn;
    private javax.swing.JButton btnShowIssue;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCreateIssuesApartmentName1;
    private javax.swing.JLabel lblCreateIssuesDescription1;
    private javax.swing.JLabel lblCreateIssuesIssueType1;
    private javax.swing.JLayeredPane pnlAnnouncement;
    private javax.swing.JPanel pnlCreateIssue1;
    private javax.swing.JPanel pnlShowIssue1;
    private javax.swing.JTable tblShowAnn;
    private javax.swing.JTextField txtTopic;
    private javax.swing.JTextField txtWing;
    // End of variables declaration//GEN-END:variables
}
