/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ResidencyManagement;

import com.mongodb.MongoClient;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import static com.mongodb.client.model.Filters.and;
import java.awt.Color;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import org.bson.Document;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sandesh
 */
public class Issues extends javax.swing.JFrame {

    /**
     * Creates new form Issues
     */
    String username;
    public Issues() {
        this.getContentPane().setBackground(new Color(72,209,204));
        initComponents();
        pnlIssue.removeAll();
        pnlIssue.revalidate();
                
    }
    public Issues(String username) {
        this.getContentPane().setBackground(new Color(72,209,204));
        initComponents();
        pnlIssue.removeAll();
        pnlIssue.revalidate();
               this.username=username; 
    }
     public void infoMessage(String message,String title)
    {
        JOptionPane.showMessageDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnShowIssue = new javax.swing.JButton();
        btnMyIssue = new javax.swing.JButton();
        btnCreateIssue = new javax.swing.JButton();
        pnlIssue = new javax.swing.JLayeredPane();
        pnlShowIssue = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblShowUsers1 = new javax.swing.JTable();
        pnlCreateIssue = new javax.swing.JPanel();
        lblCreateIssuesFirstName = new javax.swing.JLabel();
        txtCreateIssuesFirstName = new javax.swing.JTextField();
        lblCreateIssuesIssueType = new javax.swing.JLabel();
        cboxCreateIssuesIssueType = new javax.swing.JComboBox<>();
        lblCreateIssuesDescription = new javax.swing.JLabel();
        btnIssuesSubmit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        pnlMyIssues = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnBackFlatOwnerIssues = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(72, 209, 204));

        btnShowIssue.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnShowIssue.setText("Show Issues");
        btnShowIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowIssueActionPerformed(evt);
            }
        });

        btnMyIssue.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnMyIssue.setText("My Issues");
        btnMyIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyIssueActionPerformed(evt);
            }
        });

        btnCreateIssue.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnCreateIssue.setText("File Issue");
        btnCreateIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateIssueActionPerformed(evt);
            }
        });

        pnlIssue.setBackground(new java.awt.Color(72, 209, 204));

        pnlShowIssue.setBackground(new java.awt.Color(72, 209, 204));
        pnlShowIssue.setAutoscrolls(true);
        pnlShowIssue.setPreferredSize(new java.awt.Dimension(1370, 800));

        tblShowUsers1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tblShowUsers1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Issue ID", "Date", "Issue Type", "Flat No", "Issue", "Status"
            }
        ));
        tblShowUsers1.setRequestFocusEnabled(false);
        tblShowUsers1.setRowHeight(30);
        jScrollPane2.setViewportView(tblShowUsers1);
        if (tblShowUsers1.getColumnModel().getColumnCount() > 0) {
            tblShowUsers1.getColumnModel().getColumn(4).setMinWidth(200);
            tblShowUsers1.getColumnModel().getColumn(4).setPreferredWidth(200);
            tblShowUsers1.getColumnModel().getColumn(4).setMaxWidth(200);
        }

        javax.swing.GroupLayout pnlShowIssueLayout = new javax.swing.GroupLayout(pnlShowIssue);
        pnlShowIssue.setLayout(pnlShowIssueLayout);
        pnlShowIssueLayout.setHorizontalGroup(
            pnlShowIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowIssueLayout.createSequentialGroup()
                .addGap(136, 136, 136)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 996, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(238, Short.MAX_VALUE))
        );
        pnlShowIssueLayout.setVerticalGroup(
            pnlShowIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowIssueLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );

        pnlCreateIssue.setBackground(new java.awt.Color(72, 209, 204));
        pnlCreateIssue.setPreferredSize(new java.awt.Dimension(1370, 800));

        lblCreateIssuesFirstName.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblCreateIssuesFirstName.setText("Flat No");

        txtCreateIssuesFirstName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtCreateIssuesFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCreateIssuesFirstNameActionPerformed(evt);
            }
        });

        lblCreateIssuesIssueType.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblCreateIssuesIssueType.setText("Issue Type");

        cboxCreateIssuesIssueType.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        cboxCreateIssuesIssueType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maintenance", "Electricity", "Water Supply", "Ceiling Cracks", "Rent", "Repaint", "Furniture" }));
        cboxCreateIssuesIssueType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCreateIssuesIssueTypeActionPerformed(evt);
            }
        });

        lblCreateIssuesDescription.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblCreateIssuesDescription.setText("Description");

        btnIssuesSubmit.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        btnIssuesSubmit.setText("Submit");
        btnIssuesSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssuesSubmitActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        javax.swing.GroupLayout pnlCreateIssueLayout = new javax.swing.GroupLayout(pnlCreateIssue);
        pnlCreateIssue.setLayout(pnlCreateIssueLayout);
        pnlCreateIssueLayout.setHorizontalGroup(
            pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateIssueLayout.createSequentialGroup()
                .addGroup(pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCreateIssueLayout.createSequentialGroup()
                        .addGap(403, 403, 403)
                        .addGroup(pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblCreateIssuesIssueType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblCreateIssuesFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblCreateIssuesDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(114, 114, 114)
                        .addGroup(pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cboxCreateIssuesIssueType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCreateIssuesFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCreateIssueLayout.createSequentialGroup()
                        .addGap(515, 515, 515)
                        .addComponent(btnIssuesSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(445, Short.MAX_VALUE))
        );
        pnlCreateIssueLayout.setVerticalGroup(
            pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCreateIssueLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCreateIssuesFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCreateIssuesFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxCreateIssuesIssueType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateIssuesIssueType, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(pnlCreateIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCreateIssuesDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(btnIssuesSubmit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(191, 191, 191))
        );

        pnlMyIssues.setBackground(new java.awt.Color(72, 209, 204));
        pnlMyIssues.setPreferredSize(new java.awt.Dimension(1370, 800));

        jTable1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Issue ID", "Date", "Issue Type", "Issue", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel1.setText("Enter Issue ID");

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 24)); // NOI18N
        jLabel2.setText("Delete Issue");

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        jButton1.setText("Delete");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlMyIssuesLayout = new javax.swing.GroupLayout(pnlMyIssues);
        pnlMyIssues.setLayout(pnlMyIssuesLayout);
        pnlMyIssuesLayout.setHorizontalGroup(
            pnlMyIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyIssuesLayout.createSequentialGroup()
                .addGroup(pnlMyIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMyIssuesLayout.createSequentialGroup()
                        .addGap(333, 333, 333)
                        .addComponent(jLabel1)
                        .addGap(42, 42, 42)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107)
                        .addComponent(jButton1))
                    .addGroup(pnlMyIssuesLayout.createSequentialGroup()
                        .addGap(478, 478, 478)
                        .addComponent(jLabel2))
                    .addGroup(pnlMyIssuesLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 953, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(293, Short.MAX_VALUE))
        );
        pnlMyIssuesLayout.setVerticalGroup(
            pnlMyIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMyIssuesLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(16, 16, 16)
                .addGroup(pnlMyIssuesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addContainerGap(208, Short.MAX_VALUE))
        );

        pnlIssue.setLayer(pnlShowIssue, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlIssue.setLayer(pnlCreateIssue, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlIssue.setLayer(pnlMyIssues, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlIssueLayout = new javax.swing.GroupLayout(pnlIssue);
        pnlIssue.setLayout(pnlIssueLayout);
        pnlIssueLayout.setHorizontalGroup(
            pnlIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1400, Short.MAX_VALUE)
            .addGroup(pnlIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlIssueLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(pnlShowIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
            .addGroup(pnlIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlIssueLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(pnlCreateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
            .addGroup(pnlIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlIssueLayout.createSequentialGroup()
                    .addGap(15, 15, 15)
                    .addComponent(pnlMyIssues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(15, Short.MAX_VALUE)))
        );
        pnlIssueLayout.setVerticalGroup(
            pnlIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
            .addGroup(pnlIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlIssueLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlShowIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(pnlIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlIssueLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlCreateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(pnlIssueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlIssueLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlMyIssues, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btnBackFlatOwnerIssues.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnBackFlatOwnerIssues.setText("< Back");
        btnBackFlatOwnerIssues.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackFlatOwnerIssuesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnShowIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnMyIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnCreateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnBackFlatOwnerIssues, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2776, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlIssue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBackFlatOwnerIssues, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(btnCreateIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnShowIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50)
                        .addComponent(btnMyIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(896, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnShowIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowIssueActionPerformed
        // TODO add your handling code here:
        pnlIssue.removeAll();
        pnlIssue.revalidate();
        pnlIssue.add(pnlShowIssue);
        pnlIssue.revalidate();
        String ColumnName[] = {"Issue Id" ,"Date", "Issue Type", "Flat No", "Issue", "Status"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(ColumnName);
        tblShowUsers1.setModel(model);
        try{
            MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
             MongoDatabase db = mongo.getDatabase("RESIDEM");
//             db.createCollection("IssuesDB");
             MongoCollection<Document> IssuesDB = db.getCollection("IssuesDB");
             
                    FindIterable<Document> iterable =  IssuesDB.find ();
                    MongoCursor<Document> cursor = iterable.iterator();
                    while(cursor.hasNext()){
                        Document entry = cursor.next();
                        model.addRow( new Object[]{ entry.get("issueid"), entry.get("date"), entry.get("issueType"), entry.get("flatNo"), entry.get("issue"), entry.get("status") });                        
                    }
                   
                  
               mongo.close();
        }
        catch(Exception e){
            System.out.print(e);
        }
        
    }//GEN-LAST:event_btnShowIssueActionPerformed

    private void btnMyIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyIssueActionPerformed
        // TODO add your handling code here:
        pnlIssue.removeAll();
        pnlIssue.revalidate();
        pnlIssue.add(pnlMyIssues);
        pnlIssue.revalidate();
        String ColumnName[] = {"Issue Id" ,"Date", "Issue Type", "Issue", "Status"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(ColumnName);
        jTable1.setModel(model);
        try{
            MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
             MongoDatabase db = mongo.getDatabase("RESIDEM");
             //db.createCollection("IssuesDB");
             MongoCollection<Document> IssuesDB = db.getCollection("IssuesDB");
             
                    FindIterable<Document> iterable =  IssuesDB.find (Filters.eq("flatNo",username));
                    System.out.println(username);
                    MongoCursor<Document> cursor = iterable.iterator();
                    while(cursor.hasNext()){
                        Document entry = cursor.next();
                        model.addRow( new Object[]{ entry.get("issueid"), entry.get("date"), entry.get("issueType"), entry.get("issue"), entry.get("status") });                        
                    }
                   
                  
                 mongo.close();
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnMyIssueActionPerformed

    private void btnCreateIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateIssueActionPerformed
        // TODO add your handling code here:
        pnlIssue.removeAll();
        pnlIssue.revalidate();
        pnlIssue.add(pnlCreateIssue);
        pnlIssue.revalidate();
        
    }//GEN-LAST:event_btnCreateIssueActionPerformed

    private void btnIssuesSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssuesSubmitActionPerformed
        // TODO add your handling code here:
        String FlatNo = txtCreateIssuesFirstName.getText();
        String IssueType = cboxCreateIssuesIssueType.getSelectedItem().toString();
        String Issue = jTextArea2.getText();
        try{
            MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
             MongoDatabase db = mongo.getDatabase("RESIDEM");
//             db.createCollection("IssuesDB");
             MongoCollection<Document> IssuesDB = db.getCollection("IssuesDB");
             DateFormat df = new SimpleDateFormat("dd/MM/yy HH:mm:ss");
            Date dateobj = new Date();
//            System.out.println(df.format(dateobj));
            String postDate = df.format(dateobj);
            int generatedIssueID;
            while(true){
                    Random rand = new Random();
                    generatedIssueID = rand.nextInt(100000); 
                    FindIterable<Document> iterable =  IssuesDB.find ( Filters.eq("issueid", generatedIssueID) );
                    MongoCursor<Document> cursor = iterable.iterator();
                    if(!(cursor.hasNext())){
                        break;
                    }
           }
            
            IssuesDB.insertOne(new Document("issueid" , generatedIssueID).append("flatNo", FlatNo).append("issueType", IssueType).append("issue", Issue).append("date", postDate));
            txtCreateIssuesFirstName.setText("");
            jTextArea2.setText("");
            this.dispose();
            new Issues(username).setVisible(true);
             infoMessage("Issue #" + generatedIssueID   + " Added!", "Issue Logged Successful!");
                  
                   
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnIssuesSubmitActionPerformed

    private void cboxCreateIssuesIssueTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCreateIssuesIssueTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboxCreateIssuesIssueTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String s=jTextField1.getText();
        int id=Integer.parseInt(s);
        try{
            MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
             MongoDatabase db = mongo.getDatabase("RESIDEM");
             //db.createCollection("IssuesDB");
             MongoCollection<Document> IssuesDB = db.getCollection("IssuesDB");
             
                    FindIterable<Document> iterable =  IssuesDB.find (Filters.eq("issueid",id));
                    MongoCursor<Document> cursor = iterable.iterator();
                    if(cursor.hasNext()){
                        IssuesDB.deleteOne(Filters.eq("issueid",id));
                        infoMessage("Issue #"+id+" deleted!","Success");
                        this.dispose();
                        new Issues(username).setVisible(true);
                    }
                    else
                    {
                        infoMessage("Issue #"+id+" Not Found!","Failure");
                    }
                   
                  //mongo.close();
                   
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void btnBackFlatOwnerIssuesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackFlatOwnerIssuesActionPerformed
        // TODO add your handling code here:
        new com.FlatOwner(username).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackFlatOwnerIssuesActionPerformed

    private void txtCreateIssuesFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCreateIssuesFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCreateIssuesFirstNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Issues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Issues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Issues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Issues.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Issues().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBackFlatOwnerIssues;
    private javax.swing.JButton btnCreateIssue;
    private javax.swing.JButton btnIssuesSubmit;
    private javax.swing.JButton btnMyIssue;
    private javax.swing.JButton btnShowIssue;
    private javax.swing.JComboBox<String> cboxCreateIssuesIssueType;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblCreateIssuesDescription;
    private javax.swing.JLabel lblCreateIssuesFirstName;
    private javax.swing.JLabel lblCreateIssuesIssueType;
    private javax.swing.JPanel pnlCreateIssue;
    private javax.swing.JLayeredPane pnlIssue;
    private javax.swing.JPanel pnlMyIssues;
    private javax.swing.JPanel pnlShowIssue;
    private javax.swing.JTable tblShowUsers1;
    private javax.swing.JTextField txtCreateIssuesFirstName;
    // End of variables declaration//GEN-END:variables
}
