/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ResidencyManagement;

//import com.mongodb.client.MongoDatabase; 

import com.ResidencyManagement.Announcement;
import com.mongodb.MongoClient;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import static com.mongodb.client.model.Filters.and;
import static com.mongodb.client.model.Filters.eq;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;
import org.bson.conversions.Bson;

//import com.mongodb.MongoClient; 
//import com.mongodb.MongoCredential;  
//import javax.swing.JOptionPane;

/**
 *
 * @author Sandesh
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    CardLayout card=new CardLayout(0, 0);
    public User() {
        this.getContentPane().setBackground(new Color(72,209,204));
        initComponents();
    }
     public void infoMessage(String message,String title)
    {
        JOptionPane.showMessageDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackButton = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();
        pnlUser = new javax.swing.JLayeredPane();
        pnlShowUser1 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        lblUpdateUserFirstName3 = new javax.swing.JLabel();
        txtSFlatNo = new javax.swing.JTextField();
        btnSearchUser = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblAdminShowUsers = new javax.swing.JTable();
        pnlDeleteUser1 = new javax.swing.JLayeredPane();
        lblFirstName2 = new javax.swing.JLabel();
        lblLastName2 = new javax.swing.JLabel();
        lblMobileNumber2 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        txtFlatNo = new javax.swing.JTextField();
        btnSubmitUser2 = new javax.swing.JButton();
        lblMobileNumber3 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnShowUsers1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(72, 209, 204));

        BackButton.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        BackButton.setText("< Back");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });

        btnDeleteUser.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnDeleteUser.setText("Delete User");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        pnlUser.setBackground(new java.awt.Color(72, 209, 204));
        pnlUser.setPreferredSize(new java.awt.Dimension(1400, 810));
        pnlUser.setLayout(new java.awt.CardLayout());

        pnlShowUser1.setBackground(new java.awt.Color(72, 209, 204));
        pnlShowUser1.setAutoscrolls(true);
        pnlShowUser1.setPreferredSize(new java.awt.Dimension(1370, 800));

        jButton2.setText("stupid");

        lblUpdateUserFirstName3.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblUpdateUserFirstName3.setText("Flat No");

        txtSFlatNo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtSFlatNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSFlatNoActionPerformed(evt);
            }
        });

        btnSearchUser.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        btnSearchUser.setText("Search");
        btnSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUserActionPerformed(evt);
            }
        });

        tblAdminShowUsers.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tblAdminShowUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flat No", "Name", "Mobile No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblAdminShowUsers.setRequestFocusEnabled(false);
        tblAdminShowUsers.setRowHeight(30);
        jScrollPane1.setViewportView(tblAdminShowUsers);

        javax.swing.GroupLayout pnlShowUser1Layout = new javax.swing.GroupLayout(pnlShowUser1);
        pnlShowUser1.setLayout(pnlShowUser1Layout);
        pnlShowUser1Layout.setHorizontalGroup(
            pnlShowUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowUser1Layout.createSequentialGroup()
                .addGroup(pnlShowUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlShowUser1Layout.createSequentialGroup()
                        .addGap(488, 488, 488)
                        .addComponent(jButton2))
                    .addGroup(pnlShowUser1Layout.createSequentialGroup()
                        .addGap(318, 318, 318)
                        .addComponent(lblUpdateUserFirstName3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(txtSFlatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(btnSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlShowUser1Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(149, 383, Short.MAX_VALUE))
        );
        pnlShowUser1Layout.setVerticalGroup(
            pnlShowUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowUser1Layout.createSequentialGroup()
                .addGroup(pnlShowUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlShowUser1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlShowUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUpdateUserFirstName3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSFlatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlShowUser1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(467, 467, 467)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlUser.add(pnlShowUser1, "card3");

        pnlDeleteUser1.setPreferredSize(new java.awt.Dimension(1370, 800));

        lblFirstName2.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblFirstName2.setText("First Name");

        lblLastName2.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblLastName2.setText("Last Name");

        lblMobileNumber2.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblMobileNumber2.setText("Flat No");

        txtFirstName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        txtLastName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        txtFlatNo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        btnSubmitUser2.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        btnSubmitUser2.setText("Delete");
        btnSubmitUser2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitUser2ActionPerformed(evt);
            }
        });

        lblMobileNumber3.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblMobileNumber3.setText("Password");

        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        pnlDeleteUser1.setLayer(lblFirstName2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlDeleteUser1.setLayer(lblLastName2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlDeleteUser1.setLayer(lblMobileNumber2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlDeleteUser1.setLayer(txtFirstName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlDeleteUser1.setLayer(txtLastName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlDeleteUser1.setLayer(txtFlatNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlDeleteUser1.setLayer(btnSubmitUser2, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlDeleteUser1.setLayer(lblMobileNumber3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlDeleteUser1.setLayer(txtPassword, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlDeleteUser1Layout = new javax.swing.GroupLayout(pnlDeleteUser1);
        pnlDeleteUser1.setLayout(pnlDeleteUser1Layout);
        pnlDeleteUser1Layout.setHorizontalGroup(
            pnlDeleteUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteUser1Layout.createSequentialGroup()
                .addGroup(pnlDeleteUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDeleteUser1Layout.createSequentialGroup()
                        .addGap(350, 350, 350)
                        .addGroup(pnlDeleteUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblMobileNumber2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(lblFirstName2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(lblLastName2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(lblMobileNumber3, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlDeleteUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFlatNo, javax.swing.GroupLayout.DEFAULT_SIZE, 350, Short.MAX_VALUE)
                            .addComponent(txtFirstName)
                            .addComponent(txtLastName)
                            .addComponent(txtPassword)))
                    .addGroup(pnlDeleteUser1Layout.createSequentialGroup()
                        .addGap(444, 444, 444)
                        .addComponent(btnSubmitUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlDeleteUser1Layout.setVerticalGroup(
            pnlDeleteUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDeleteUser1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDeleteUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFirstName2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(pnlDeleteUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastName2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(pnlDeleteUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMobileNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFlatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(pnlDeleteUser1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblMobileNumber3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(txtPassword))
                .addGap(83, 83, 83)
                .addComponent(btnSubmitUser2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlUser.add(pnlDeleteUser1, "card5");

        btnShowUsers1.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnShowUsers1.setText("Show Users");
        btnShowUsers1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowUsers1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnShowUsers1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addComponent(pnlUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2851, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(BackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnShowUsers1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnDeleteUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(1213, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        // TODO add your handling code here:
        /*card.show(pnlShowUser, "Show");
        pnlCreateUser.setVisible(false);
        pnlUpdateUser.setVisible(false);
        pnlDeleteUser.setVisible(false);
        pnlShowUser.setVisible(false);*/
//        pnlUser.removeAll();
//        //pnlUser.repaint();
//        pnlUser.revalidate();
//        pnlUser.add(pnlShowUser1);
//        //pnlUser.repaint();
//        pnlUser.revalidate();
        new com.Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BackButtonActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        // TODO add your handling code here:
        /*pnlCreateUser.setVisible(false);
        pnlUpdateUser.setVisible(false);
        pnlShowUser.setVisible(false);
        pnlDeleteUser.setVisible(true);*/
        pnlUser.removeAll();
        //pnlUser.repaint();
        pnlUser.revalidate();
        pnlUser.add(pnlDeleteUser1);
        //pnlUser.repaint();
        pnlUser.revalidate();
        
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    private void txtSFlatNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSFlatNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSFlatNoActionPerformed

    private void btnSubmitUser2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitUser2ActionPerformed
        // TODO add your handling code here:
        String fname = txtFirstName.getText();
        String lname = txtLastName.getText();
        String flatNo = txtFlatNo.getText();
        String password = txtPassword.getText();//this would be the password set for the flatNo
        
        
         try{
            MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
             MongoDatabase db = mongo.getDatabase("RESIDEM");
             //db.createCollection("IssuesDB");
             MongoCollection<Document> FlatOwnerDB = db.getCollection("FlatOwnerDB");
             
                    FindIterable<Document> iterable =  FlatOwnerDB.find(and ( Filters.eq("flatNo", flatNo)  , Filters.eq("password", password)  , Filters.eq("firstname", fname)  , Filters.eq("lastname", lname) ) );     
//                    System.out.println(findUser);
                    MongoCursor<Document> cursor = iterable.iterator();
                    if(cursor.hasNext()){
                        Bson filter = eq("flatNo", flatNo);
                        FlatOwnerDB.deleteMany(filter);
                        infoMessage("Record Deleted! " , "Success");
                    }
                    else{
                        infoMessage( "Record Not Found! Please Try Again","Error! " );
                    }
                   
                  
                 mongo.close();
        }
        catch(Exception e){
            System.out.print(e);
        }
        
        
    }//GEN-LAST:event_btnSubmitUser2ActionPerformed

    private void btnShowUsers1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowUsers1ActionPerformed
        // TODO add your handling code here:
         pnlUser.removeAll();
        //pnlUser.repaint();
        pnlUser.revalidate();
        pnlUser.add(pnlShowUser1);
        //pnlUser.repaint();
        pnlUser.revalidate();
    }//GEN-LAST:event_btnShowUsers1ActionPerformed

    private void btnSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUserActionPerformed
        // TODO add your handling code here:
//        String sFlatNo = txtSFlatNo.getText();
         String findUser = txtSFlatNo.getText();
        String ColumnName[] = {"Flat No" ,"Name", "Mobile No"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(ColumnName);
        tblAdminShowUsers.setModel(model);
        try{
            MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
             MongoDatabase db = mongo.getDatabase("RESIDEM");
             //db.createCollection("IssuesDB");
             MongoCollection<Document> FlatOwnerDB = db.getCollection("FlatOwnerDB");
             
                    FindIterable<Document> iterable =  FlatOwnerDB.find (Filters.eq("flatNo", findUser));
                    System.out.println(findUser);
                    MongoCursor<Document> cursor = iterable.iterator();
                    if(cursor.hasNext()){
                        Document entry = cursor.next();
                        String username =  entry.get("firstname") + " "+entry.get("lastname");
                        model.addRow( new Object[]{ entry.get("flatNo"), username , entry.get("mobileNo")});        
                         infoMessage("Success " , "Record Found!");
                         tblAdminShowUsers.setVisible(false);
                         tblAdminShowUsers.setVisible(true);
                    }
                    else{
                        infoMessage("Error! " , "Record Not Found! Please Try Again");
                    }
                   
                  
                 mongo.close();
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnSearchUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new User().setVisible(true);
        });
        
         //MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnSearchUser;
    private javax.swing.JButton btnShowUsers1;
    private javax.swing.JButton btnSubmitUser2;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFirstName2;
    private javax.swing.JLabel lblLastName2;
    private javax.swing.JLabel lblMobileNumber2;
    private javax.swing.JLabel lblMobileNumber3;
    private javax.swing.JLabel lblUpdateUserFirstName3;
    private javax.swing.JLayeredPane pnlDeleteUser1;
    private javax.swing.JPanel pnlShowUser1;
    private javax.swing.JLayeredPane pnlUser;
    private javax.swing.JTable tblAdminShowUsers;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtFlatNo;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtSFlatNo;
    // End of variables declaration//GEN-END:variables
}
