/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ResidencyManagement;

//import com.mongodb.client.MongoDatabase; 

import com.mongodb.MongoClient;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import java.awt.Color;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

//import com.mongodb.MongoCredential;  
//import javax.swing.JOptionPane;

/**
 *
 * @author Sandesh
 */
public class Visitor extends javax.swing.JFrame {

    /**
     * Creates new form User
     */
    public Visitor() {
        this.getContentPane().setBackground(new Color(72,209,204));
        initComponents();
         pnlVisitor.removeAll();
        pnlVisitor.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCreateUser = new javax.swing.JButton();
        btnShowUsers = new javax.swing.JButton();
        pnlVisitor = new javax.swing.JLayeredPane();
        pnlShowUser = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSecurityShowVisitors = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(72, 209, 204));

        btnCreateUser.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnCreateUser.setText("< Back");
        btnCreateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateUserActionPerformed(evt);
            }
        });

        btnShowUsers.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        btnShowUsers.setText("Show Visits");
        btnShowUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowUsersActionPerformed(evt);
            }
        });

        pnlVisitor.setBackground(new java.awt.Color(72, 209, 204));

        pnlShowUser.setBackground(new java.awt.Color(72, 209, 204));
        pnlShowUser.setAutoscrolls(true);
        pnlShowUser.setPreferredSize(new java.awt.Dimension(1370, 800));

        jButton1.setText("stupid");

        javax.swing.GroupLayout pnlShowUserLayout = new javax.swing.GroupLayout(pnlShowUser);
        pnlShowUser.setLayout(pnlShowUserLayout);
        pnlShowUserLayout.setHorizontalGroup(
            pnlShowUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowUserLayout.createSequentialGroup()
                .addGap(488, 488, 488)
                .addComponent(jButton1)
                .addGap(823, 823, 823))
        );
        pnlShowUserLayout.setVerticalGroup(
            pnlShowUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlShowUserLayout.createSequentialGroup()
                .addGap(955, 955, 955)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlVisitor.setLayer(pnlShowUser, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlVisitorLayout = new javax.swing.GroupLayout(pnlVisitor);
        pnlVisitor.setLayout(pnlVisitorLayout);
        pnlVisitorLayout.setHorizontalGroup(
            pnlVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisitorLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlShowUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlVisitorLayout.setVerticalGroup(
            pnlVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVisitorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlShowUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane3.setBackground(new java.awt.Color(72, 209, 204));

        tblSecurityShowVisitors.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tblSecurityShowVisitors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date & Time", "Name", "Visit To", "Purpose", "Vehicle No", "Number of People", "Mobile No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSecurityShowVisitors.setRequestFocusEnabled(false);
        tblSecurityShowVisitors.setRowHeight(30);
        jScrollPane3.setViewportView(tblSecurityShowVisitors);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnShowUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 955, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(2756, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCreateUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnShowUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(535, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateUserActionPerformed
        // TODO add your handling code here:
//        pnlVisitor.removeAll();
//        pnlVisitor.revalidate();
//        pnlVisitor.add(pnlCreateUser);
//        pnlVisitor.revalidate();        
        new com.Admin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCreateUserActionPerformed

    private void btnShowUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowUsersActionPerformed
        // TODO add your handling code here:
        pnlVisitor.removeAll();
        pnlVisitor.revalidate();
        pnlVisitor.add(pnlShowUser);
        pnlVisitor.revalidate();
        
         String ColumnName[] = {"DateTime" ,"Name", "Visit To", "Purpose", "Vehicle No", "NoOfPeople", "MobileNo"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(ColumnName);
        tblSecurityShowVisitors.setModel(model);
        try{
            MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
             MongoDatabase db = mongo.getDatabase("RESIDEM");
             //db.createCollection("IssuesDB");
             MongoCollection<Document> VisitorsDB = db.getCollection("VisitorsDB");
             
                    FindIterable<Document> iterable =  VisitorsDB.find ();
//                    System.out.println(username);
                    MongoCursor<Document> cursor = iterable.iterator();
                    while(cursor.hasNext()){
                        Document entry = cursor.next();
                        model.addRow( new Object[]{ entry.get("DateTime"), entry.get("Name"), entry.get("VisitTo"), entry.get("Purpose"), entry.get("VehicleNo"), entry.get("NoOfPeople"), entry.get("MobileNo") });                        
                    }
                   
                  
                 mongo.close();
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnShowUsersActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Visitor().setVisible(true);
        });
        
         //MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreateUser;
    private javax.swing.JButton btnShowUsers;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel pnlShowUser;
    private javax.swing.JLayeredPane pnlVisitor;
    private javax.swing.JTable tblSecurityShowVisitors;
    // End of variables declaration//GEN-END:variables
}
