/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com;

//import com.mongodb.client.MongoDatabase; 

//import UserLogin;
import com.mongodb.MongoClient;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import static com.mongodb.client.model.Filters.and;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

//import com.mongodb.MongoClient; 
//import com.mongodb.MongoCredential;  
//import javax.swing.JOptionPane;

/**
 *
 * @author Sandesh
 */
public class Security extends javax.swing.JFrame {

    Image img;
    public Security() {
//        this.img = Toolkit.getDefaultToolkit().getImage("D:\\alan1.jpg");
this.getContentPane().setBackground(new Color(72,209,204));
        initComponents();
    }
    
    public void infoMessage(String message,String title)
    {
        JOptionPane.showMessageDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
    }
    

/**
     * Creates new form User
     */
        /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSecurityShowUsers = new javax.swing.JButton();
        btnSecurityAddVisitor = new javax.swing.JButton();
        pnlSecurityAddVisitor = new javax.swing.JPanel();
        txtAVName = new javax.swing.JTextField();
        btnAVSubmit2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtAVVisitTo = new javax.swing.JTextField();
        txtAVPurpose = new javax.swing.JTextField();
        txtAVVehicleNo = new javax.swing.JTextField();
        txtAVNoOfPeople = new javax.swing.JTextField();
        txtAVMobileNo = new javax.swing.JTextField();
        pnlSecurityShowUsers = new javax.swing.JLayeredPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSecurityShowUsers = new javax.swing.JTable();
        lblUpdateUserFirstName1 = new javax.swing.JLabel();
        txtFindFlatNo = new javax.swing.JTextField();
        btnSearchUser = new javax.swing.JButton();
        btnSecurityShowVisitors = new javax.swing.JButton();
        btnSecurityShowAnnouncements = new javax.swing.JButton();
        pnlSecurityShowVisitors = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblSecurityShowVisitors = new javax.swing.JTable();
        pnlSecurityShowAnnouncements = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblSecurityShowAnn = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        btnSecurityLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(72, 209, 204));

        btnSecurityShowUsers.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        btnSecurityShowUsers.setText("Show Users");
        btnSecurityShowUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecurityShowUsersActionPerformed(evt);
            }
        });

        btnSecurityAddVisitor.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        btnSecurityAddVisitor.setText("Add Visitor");
        btnSecurityAddVisitor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecurityAddVisitorActionPerformed(evt);
            }
        });

        pnlSecurityAddVisitor.setBackground(new java.awt.Color(72, 209, 204));
        pnlSecurityAddVisitor.setAutoscrolls(true);
        pnlSecurityAddVisitor.setPreferredSize(new java.awt.Dimension(1370, 800));

        txtAVName.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtAVName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAVNameActionPerformed(evt);
            }
        });

        btnAVSubmit2.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        btnAVSubmit2.setText("Submit");
        btnAVSubmit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAVSubmit2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel1.setText("Name");

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel2.setText("Visit to");

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel3.setText("Purpose");

        jLabel4.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel4.setText("Vehicle No");

        jLabel5.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel5.setText("No. of People");

        jLabel6.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        jLabel6.setText("Mobile No.");

        txtAVVisitTo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtAVVisitTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAVVisitToActionPerformed(evt);
            }
        });

        txtAVPurpose.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtAVPurpose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAVPurposeActionPerformed(evt);
            }
        });

        txtAVVehicleNo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtAVVehicleNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAVVehicleNoActionPerformed(evt);
            }
        });

        txtAVNoOfPeople.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtAVNoOfPeople.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAVNoOfPeopleActionPerformed(evt);
            }
        });

        txtAVMobileNo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtAVMobileNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAVMobileNoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlSecurityAddVisitorLayout = new javax.swing.GroupLayout(pnlSecurityAddVisitor);
        pnlSecurityAddVisitor.setLayout(pnlSecurityAddVisitorLayout);
        pnlSecurityAddVisitorLayout.setHorizontalGroup(
            pnlSecurityAddVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecurityAddVisitorLayout.createSequentialGroup()
                .addGroup(pnlSecurityAddVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSecurityAddVisitorLayout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addGroup(pnlSecurityAddVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(82, 82, 82)
                        .addGroup(pnlSecurityAddVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAVVisitTo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAVName, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAVPurpose, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAVVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAVNoOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAVMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlSecurityAddVisitorLayout.createSequentialGroup()
                        .addGap(496, 496, 496)
                        .addComponent(btnAVSubmit2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnlSecurityAddVisitorLayout.setVerticalGroup(
            pnlSecurityAddVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecurityAddVisitorLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(pnlSecurityAddVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAVName, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(pnlSecurityAddVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAVVisitTo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlSecurityAddVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAVPurpose, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(pnlSecurityAddVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAVVehicleNo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(pnlSecurityAddVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAVNoOfPeople, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(pnlSecurityAddVisitorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAVMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(btnAVSubmit2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pnlSecurityShowUsers.setBackground(new java.awt.Color(72, 209, 204));
        pnlSecurityShowUsers.setPreferredSize(new java.awt.Dimension(1370, 800));

        tblSecurityShowUsers.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tblSecurityShowUsers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flat No", "Name", "Mobile No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSecurityShowUsers.setRequestFocusEnabled(false);
        tblSecurityShowUsers.setRowHeight(30);
        jScrollPane1.setViewportView(tblSecurityShowUsers);

        lblUpdateUserFirstName1.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblUpdateUserFirstName1.setText("Flat No");

        txtFindFlatNo.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        txtFindFlatNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFindFlatNoActionPerformed(evt);
            }
        });

        btnSearchUser.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        btnSearchUser.setText("Search");
        btnSearchUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchUserActionPerformed(evt);
            }
        });

        pnlSecurityShowUsers.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlSecurityShowUsers.setLayer(lblUpdateUserFirstName1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlSecurityShowUsers.setLayer(txtFindFlatNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        pnlSecurityShowUsers.setLayer(btnSearchUser, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout pnlSecurityShowUsersLayout = new javax.swing.GroupLayout(pnlSecurityShowUsers);
        pnlSecurityShowUsers.setLayout(pnlSecurityShowUsersLayout);
        pnlSecurityShowUsersLayout.setHorizontalGroup(
            pnlSecurityShowUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecurityShowUsersLayout.createSequentialGroup()
                .addGroup(pnlSecurityShowUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSecurityShowUsersLayout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(lblUpdateUserFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtFindFlatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(btnSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlSecurityShowUsersLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 948, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(274, Short.MAX_VALUE))
        );
        pnlSecurityShowUsersLayout.setVerticalGroup(
            pnlSecurityShowUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecurityShowUsersLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(pnlSecurityShowUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpdateUserFirstName1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFindFlatNo, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchUser, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnSecurityShowVisitors.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        btnSecurityShowVisitors.setText("Review Visitors");
        btnSecurityShowVisitors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecurityShowVisitorsActionPerformed(evt);
            }
        });

        btnSecurityShowAnnouncements.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        btnSecurityShowAnnouncements.setText("Show Announcements");
        btnSecurityShowAnnouncements.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecurityShowAnnouncementsActionPerformed(evt);
            }
        });

        pnlSecurityShowVisitors.setBackground(new java.awt.Color(72, 209, 204));
        pnlSecurityShowVisitors.setPreferredSize(new java.awt.Dimension(1370, 800));

        tblSecurityShowVisitors.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tblSecurityShowVisitors.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date & Time", "Name", "Visit To", "Purpose", "Vehicle No", "Number of People", "Mobile No"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSecurityShowVisitors.setRequestFocusEnabled(false);
        tblSecurityShowVisitors.setRowHeight(30);
        jScrollPane3.setViewportView(tblSecurityShowVisitors);

        javax.swing.GroupLayout pnlSecurityShowVisitorsLayout = new javax.swing.GroupLayout(pnlSecurityShowVisitors);
        pnlSecurityShowVisitors.setLayout(pnlSecurityShowVisitorsLayout);
        pnlSecurityShowVisitorsLayout.setHorizontalGroup(
            pnlSecurityShowVisitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecurityShowVisitorsLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 912, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );
        pnlSecurityShowVisitorsLayout.setVerticalGroup(
            pnlSecurityShowVisitorsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecurityShowVisitorsLayout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        pnlSecurityShowAnnouncements.setBackground(new java.awt.Color(72, 209, 204));
        pnlSecurityShowAnnouncements.setPreferredSize(new java.awt.Dimension(1370, 800));

        tblSecurityShowAnn.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        tblSecurityShowAnn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ann ID", "Date", "Topic", "Wing(s)", "Announcement"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblSecurityShowAnn.setRequestFocusEnabled(false);
        tblSecurityShowAnn.setRowHeight(30);
        jScrollPane4.setViewportView(tblSecurityShowAnn);

        javax.swing.GroupLayout pnlSecurityShowAnnouncementsLayout = new javax.swing.GroupLayout(pnlSecurityShowAnnouncements);
        pnlSecurityShowAnnouncements.setLayout(pnlSecurityShowAnnouncementsLayout);
        pnlSecurityShowAnnouncementsLayout.setHorizontalGroup(
            pnlSecurityShowAnnouncementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecurityShowAnnouncementsLayout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 925, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );
        pnlSecurityShowAnnouncementsLayout.setVerticalGroup(
            pnlSecurityShowAnnouncementsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSecurityShowAnnouncementsLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 493, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("SECURITY");

        btnSecurityLogout.setFont(new java.awt.Font("Comic Sans MS", 0, 20)); // NOI18N
        btnSecurityLogout.setText("Logout");
        btnSecurityLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecurityLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSecurityShowUsers, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                                .addComponent(btnSecurityAddVisitor, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btnSecurityShowVisitors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnSecurityShowAnnouncements, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnSecurityLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlSecurityShowUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlSecurityShowVisitors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlSecurityAddVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pnlSecurityShowAnnouncements, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(560, 560, 560)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlSecurityShowUsers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(pnlSecurityShowVisitors, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSecurityShowUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnSecurityAddVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(btnSecurityShowVisitors, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnSecurityShowAnnouncements, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(btnSecurityLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlSecurityAddVisitor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlSecurityShowAnnouncements, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSecurityShowUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecurityShowUsersActionPerformed
        // TODO add your handling code here:
        pnlSecurityAddVisitor.setVisible(false);
        pnlSecurityShowVisitors.setVisible(false);
        pnlSecurityShowAnnouncements.setVisible(false);
        pnlSecurityShowUsers.setVisible(true);
       
    }//GEN-LAST:event_btnSecurityShowUsersActionPerformed

    private void btnSecurityAddVisitorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecurityAddVisitorActionPerformed
        // TODO add your handling code here:
        pnlSecurityShowUsers.setVisible(false);
        pnlSecurityShowVisitors.setVisible(false);
        pnlSecurityShowAnnouncements.setVisible(false);
        pnlSecurityAddVisitor.setVisible(true);
    }//GEN-LAST:event_btnSecurityAddVisitorActionPerformed

    private void btnSecurityShowVisitorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecurityShowVisitorsActionPerformed
        // TODO add your handling code here:
        pnlSecurityShowUsers.setVisible(false);
        pnlSecurityShowAnnouncements.setVisible(false);
        pnlSecurityAddVisitor.setVisible(false);
        pnlSecurityShowVisitors.setVisible(true);
        String ColumnName[] = {"DateTime" ,"Name", "Visit To", "Purpose", "Vehicle No", "NoOfPeople", "MobileNo"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(ColumnName);
        tblSecurityShowVisitors.setModel(model);
        try{
            MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
             MongoDatabase db = mongo.getDatabase("RESIDEM");
             //db.createCollection("IssuesDB");
             MongoCollection<Document> VisitorsDB = db.getCollection("VisitorsDB");
             
                    FindIterable<Document> iterable =  VisitorsDB.find ();
//                    System.out.println(username);
                    MongoCursor<Document> cursor = iterable.iterator();
                    while(cursor.hasNext()){
                        Document entry = cursor.next();
                        model.addRow( new Object[]{ entry.get("DateTime"), entry.get("Name"), entry.get("VisitTo"), entry.get("Purpose"), entry.get("VehicleNo"), entry.get("NoOfPeople"), entry.get("MobileNo") });                        
                    }
                   
                  
                 mongo.close();
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnSecurityShowVisitorsActionPerformed

    private void btnSecurityShowAnnouncementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecurityShowAnnouncementsActionPerformed
        // TODO add your handling code here:
        pnlSecurityShowUsers.setVisible(false);
        pnlSecurityShowVisitors.setVisible(false);
        pnlSecurityAddVisitor.setVisible(false);
        pnlSecurityShowAnnouncements.setVisible(true);
         String ColumnName[] = {"Ann ID" ,"Date", "Topic", "Wing(s)", "Announcement"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(ColumnName);
        tblSecurityShowAnn.setModel(model);
        try{
            try (MongoClient mongo = new MongoClient( "localhost" , 27017 )) {
                MongoDatabase db = mongo.getDatabase("RESIDEM");
                //db.createCollection("AnnouncementsDB");
                MongoCollection<Document> AnnouncementsDB = db.getCollection("AnnouncementsDB");
                
                FindIterable<Document> iterable =  AnnouncementsDB.find ();
                MongoCursor<Document> cursor = iterable.iterator();
                while(cursor.hasNext()){
                    Document entry = cursor.next();
                    model.addRow( new Object[]{ entry.get("annid"), entry.get("date"), entry.get("topic"), entry.get("wing"), entry.get("announcement") });
                }
            }
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnSecurityShowAnnouncementsActionPerformed

    private void txtFindFlatNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFindFlatNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFindFlatNoActionPerformed

    private void txtAVNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAVNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAVNameActionPerformed

    private void btnSearchUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchUserActionPerformed
        // TODO add your handling code here:
        String findUser = txtFindFlatNo.getText();
        String ColumnName[] = {"Flat No" ,"Name", "Mobile No"};
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(ColumnName);
        tblSecurityShowUsers.setModel(model);
        try{
            MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
             MongoDatabase db = mongo.getDatabase("RESIDEM");
             //db.createCollection("IssuesDB");
             MongoCollection<Document> FlatOwnerDB = db.getCollection("FlatOwnerDB");
             
                    FindIterable<Document> iterable =  FlatOwnerDB.find (Filters.eq("flatNo", findUser));
                    System.out.println(findUser);
                    MongoCursor<Document> cursor = iterable.iterator();
                    if(cursor.hasNext()){
                        Document entry = cursor.next();
                        String username =  entry.get("firstname") + " "+entry.get("lastname");
                        model.addRow( new Object[]{ entry.get("flatNo"), username , entry.get("mobileNo")});        
                         infoMessage("Success " , "Record Found!");
                         pnlSecurityShowUsers.setVisible(false);
                         pnlSecurityShowUsers.setVisible(true);
                    }
                    else{
                        infoMessage("Error! " , "Record Not Found! Please Try Again");
                    }
                   
                  
                 mongo.close();
        }
        catch(Exception e){
            System.out.print(e);
        }
    }//GEN-LAST:event_btnSearchUserActionPerformed

    private void txtAVVisitToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAVVisitToActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAVVisitToActionPerformed

    private void txtAVPurposeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAVPurposeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAVPurposeActionPerformed

    private void txtAVVehicleNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAVVehicleNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAVVehicleNoActionPerformed

    private void txtAVNoOfPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAVNoOfPeopleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAVNoOfPeopleActionPerformed

    private void txtAVMobileNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAVMobileNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAVMobileNoActionPerformed

    private void btnAVSubmit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAVSubmit2ActionPerformed
        // TODO add your handling code here:
        String name = txtAVName.getText();
        String Visitto = txtAVVisitTo.getText();
        String Purpose = txtAVPurpose.getText();
        String VehicleNo = txtAVVehicleNo.getText();
        int NoOfPeople = Integer.parseInt(txtAVNoOfPeople.getText());
        String MobileNo = txtAVMobileNo.getText();
        DateFormat df = new SimpleDateFormat("dd/MM/yy HH:mm:ss");
            Date dateobj = new Date();
        String visitTime = df.format(dateobj);
        try{
            MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
             MongoDatabase db = mongo.getDatabase("RESIDEM");
//             db.createCollection("VisitorsDB");
             MongoCollection<Document> VisitorsDB = db.getCollection("VisitorsDB");
            
             VisitorsDB.insertOne(new Document("DateTime", visitTime).append("Name" , name).append("VisitTo", Visitto).append("Purpose", Purpose).append("VehicleNo", VehicleNo).append("NoOfPeople", NoOfPeople).append("MobileNo", MobileNo));
             infoMessage("Entry Added " , "Successful!");
            this.dispose();
             new Security().setVisible(true);
           
           
//             System.out.print("User successfully ")
        }
        catch(Exception e){
            System.out.print(e);
            infoMessage("Error! " , "Entry Unsuccessful!");
        }
    }//GEN-LAST:event_btnAVSubmit2ActionPerformed

    private void btnSecurityLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecurityLogoutActionPerformed
        // TODO add your handling code here:
        JOptionPane confirm = new JOptionPane();       
       int input =  confirm.showConfirmDialog(rootPane, "Do you wish to continue?");
        if(  input == JOptionPane.YES_OPTION){
            dispose();         
            System.exit(0);
         }
        else if( input == JOptionPane.NO_OPTION){
            this.dispose();
            new Security().setVisible(true);
        }
    }//GEN-LAST:event_btnSecurityLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Security.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Security.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Security.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Security.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Security().setVisible(true);
        });
        
         //MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
   
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAVSubmit2;
    private javax.swing.JButton btnSearchUser;
    private javax.swing.JButton btnSecurityAddVisitor;
    private javax.swing.JButton btnSecurityLogout;
    private javax.swing.JButton btnSecurityShowAnnouncements;
    private javax.swing.JButton btnSecurityShowUsers;
    private javax.swing.JButton btnSecurityShowVisitors;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JLabel lblUpdateUserFirstName1;
    private javax.swing.JPanel pnlSecurityAddVisitor;
    private javax.swing.JPanel pnlSecurityShowAnnouncements;
    private javax.swing.JLayeredPane pnlSecurityShowUsers;
    private javax.swing.JPanel pnlSecurityShowVisitors;
    private javax.swing.JTable tblSecurityShowAnn;
    private javax.swing.JTable tblSecurityShowUsers;
    private javax.swing.JTable tblSecurityShowVisitors;
    private javax.swing.JTextField txtAVMobileNo;
    private javax.swing.JTextField txtAVName;
    private javax.swing.JTextField txtAVNoOfPeople;
    private javax.swing.JTextField txtAVPurpose;
    private javax.swing.JTextField txtAVVehicleNo;
    private javax.swing.JTextField txtAVVisitTo;
    private javax.swing.JTextField txtFindFlatNo;
    // End of variables declaration//GEN-END:variables
}
