
import com.Admin;
import com.FlatOwner;
import com.mongodb.BasicDBObject;
import com.mongodb.client.MongoDatabase; 
import com.mongodb.MongoClient; 
import com.mongodb.MongoCredential; 
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.model.Filters;
import static com.mongodb.client.model.Filters.and;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import org.bson.Document;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Sandesh
 */
public class AdminLogin extends javax.swing.JFrame {

    /**
     * Creates new form AdminLogin
     */
    public AdminLogin() {
        initComponents();
//        this.getContentPane().setBackground(new Color(0,139,139));
//        this.getContentPane().setBackground(new Color(72,209,204));
//        this.getContentPane().setBackground(new Color(175,238,238));
        this.getContentPane().setBackground(new Color(135,206,235));
//        this.getContentPane().setBackground(new Color(0,139,139));
//        this.getContentPane().setBackground(new Color(0,139,139));
//        this.getContentPane().setBackground(new Color(0,139,139));
//        this.getContentPane().setBackground(new Color(0,139,139));
//        this.setForeground(Color.red);
        
    }

    public void infoMessage(String message,String title)
    {
        JOptionPane.showMessageDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAdminLoginID = new javax.swing.JLabel();
        txtAdminLoginID = new javax.swing.JTextField();
        lblAdminLoginPassword = new javax.swing.JLabel();
        pfAdminLoginPassword = new javax.swing.JPasswordField();
        btnAdminLoginLogin = new javax.swing.JButton();
        btnAdminLoginUserLogin = new javax.swing.JButton();
        lblAdminLogin = new javax.swing.JLabel();
        btnAdminLoginSecurityLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(30, 144, 255));
        setPreferredSize(new java.awt.Dimension(900, 600));

        lblAdminLoginID.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblAdminLoginID.setText("Username");

        txtAdminLoginID.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        lblAdminLoginPassword.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblAdminLoginPassword.setText("Password");
        lblAdminLoginPassword.setPreferredSize(new java.awt.Dimension(117, 31));

        pfAdminLoginPassword.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        btnAdminLoginLogin.setBackground(new java.awt.Color(30, 144, 255));
        btnAdminLoginLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        btnAdminLoginLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminLoginLogin.setText("Login");
        btnAdminLoginLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginLoginActionPerformed(evt);
            }
        });

        btnAdminLoginUserLogin.setBackground(new java.awt.Color(255, 223, 0));
        btnAdminLoginUserLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        btnAdminLoginUserLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminLoginUserLogin.setText("Flat Owner?");
        btnAdminLoginUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginUserLoginActionPerformed(evt);
            }
        });

        lblAdminLogin.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 36)); // NOI18N
        lblAdminLogin.setText("Admin Login");

        btnAdminLoginSecurityLogin.setBackground(new java.awt.Color(255, 0, 0));
        btnAdminLoginSecurityLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        btnAdminLoginSecurityLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnAdminLoginSecurityLogin.setText("Security?");
        btnAdminLoginSecurityLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminLoginSecurityLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnAdminLoginSecurityLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAdminLoginUserLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblAdminLoginID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblAdminLoginPassword, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAdminLoginID, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(pfAdminLoginPassword)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(320, 320, 320)
                        .addComponent(btnAdminLoginLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(lblAdminLogin)))
                .addGap(205, 207, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblAdminLogin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminLoginID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAdminLoginID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfAdminLoginPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(btnAdminLoginLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(btnAdminLoginUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnAdminLoginSecurityLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdminLoginLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginLoginActionPerformed
        // TODO add your handling code here:
        String username=txtAdminLoginID.getText();
        String password=pfAdminLoginPassword.getText();
        try{
            MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
             MongoDatabase db = mongo.getDatabase("RESIDEM");
             //db.createCollection("AdminDB");
             System.out.println("Collection created");
             MongoCollection<Document> AdminDB = db.getCollection("AdminDB");
            // Validating result in mongodb
    //        Document result = AdminDB.find(new BasicDBObject("username", username), new BasicDBObject("password", password));
           FindIterable<Document> iterable =  AdminDB.find(and ( Filters.eq("username", username)  , Filters.eq("password", password) ) );
           MongoCursor<Document> cursor = iterable.iterator();
           if(cursor.hasNext()){
                System.out.println("User has logged in");
                
               infoMessage("Welcome " + username , "Login Successful!");
            new Admin().setVisible(true);
            
            this.dispose();           
            mongo.close();

           }
           else{
               System.out.print("user login unsuccesful");
               infoMessage("Incorrect Credentials!", "Error");
           }
       }
        catch(Exception e){
            
           System.out.print(e);
            
        }
//        if(result.iterator().hasNext()){
//                  
//        }
        
        
    }//GEN-LAST:event_btnAdminLoginLoginActionPerformed

    private void btnAdminLoginUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginUserLoginActionPerformed
        // TODO add your handling code here:
        try{
            dispose();
            UserLogin u1=new UserLogin();
            u1.setVisible(true);
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnAdminLoginUserLoginActionPerformed

    private void btnAdminLoginSecurityLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminLoginSecurityLoginActionPerformed
        // TODO add your handling code here:
        new SecurityLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAdminLoginSecurityLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
         MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
         MongoDatabase db = mongo.getDatabase("RESIDEM");
         MongoCollection<Document> AdminDB = db.getCollection("AdminDB");
//         MongoCollection<Document> FlatownerDB = db.getCollection("FlatownerDB");
//         MongoCollection<Document> SecurityDB = db.getCollection("SecurityDB");
//         
//         MongoCollection<Document> IssuesDB = db.getCollection("IssuesDB");
//         MongoCollection<Document> NoticeDB = db.getCollection("NoticeDB");
//         MongoCollection<Document> ReminderDB = db.getCollection("ReminderDB");
         
         
         
         
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new AdminLogin().setVisible(true);
//            JFrame frame = new AdminLogin();
//            frame.setBackground(Color.white);
//            frame.setVisible(true);
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminLoginLogin;
    private javax.swing.JButton btnAdminLoginSecurityLogin;
    private javax.swing.JButton btnAdminLoginUserLogin;
    private javax.swing.JLabel lblAdminLogin;
    private javax.swing.JLabel lblAdminLoginID;
    private javax.swing.JLabel lblAdminLoginPassword;
    private javax.swing.JPasswordField pfAdminLoginPassword;
    private javax.swing.JTextField txtAdminLoginID;
    // End of variables declaration//GEN-END:variables
}
