/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import com.FlatOwner;
import com.Security;
import com.mongodb.MongoClient;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoCursor;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.model.Filters;
import static com.mongodb.client.model.Filters.and;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import org.bson.Document;

/**
 *
 * @author om
 */
public class SecurityLogin extends javax.swing.JFrame {

    /**
     * Creates new form UserLogin
     */
    public SecurityLogin() {
        this.getContentPane().setBackground(new Color(135,206,235));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSecurityID = new javax.swing.JLabel();
        lblSecurityPassword = new javax.swing.JLabel();
        txtSecurityID = new javax.swing.JTextField();
        btnSecurityLogin = new javax.swing.JButton();
        btnSecurityUserLogin = new javax.swing.JButton();
        pfSecurityPassword = new javax.swing.JPasswordField();
        btnSecurityAdminLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 600));

        jLabel1.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 36)); // NOI18N
        jLabel1.setText("Security Login");

        lblSecurityID.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblSecurityID.setText("Username");

        lblSecurityPassword.setFont(new java.awt.Font("Dialog", 0, 20)); // NOI18N
        lblSecurityPassword.setText("Password");

        txtSecurityID.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N

        btnSecurityLogin.setBackground(new java.awt.Color(255, 0, 0));
        btnSecurityLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        btnSecurityLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnSecurityLogin.setText("Login");
        btnSecurityLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecurityLoginActionPerformed(evt);
            }
        });

        btnSecurityUserLogin.setBackground(new java.awt.Color(255, 223, 0));
        btnSecurityUserLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        btnSecurityUserLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnSecurityUserLogin.setText("Flat Owner?");
        btnSecurityUserLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecurityUserLoginActionPerformed(evt);
            }
        });

        pfSecurityPassword.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N

        btnSecurityAdminLogin.setBackground(new java.awt.Color(30, 144, 255));
        btnSecurityAdminLogin.setFont(new java.awt.Font("Comic Sans MS", 1, 20)); // NOI18N
        btnSecurityAdminLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnSecurityAdminLogin.setText("Admin?");
        btnSecurityAdminLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecurityAdminLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(200, 200, 200)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSecurityPassword)
                    .addComponent(lblSecurityID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSecurityID, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(pfSecurityPassword))
                .addGap(317, 317, 317))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnSecurityUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSecurityAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(278, 278, 278)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(345, 345, 345)
                        .addComponent(btnSecurityLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSecurityID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSecurityID, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSecurityPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pfSecurityPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 113, Short.MAX_VALUE)
                .addComponent(btnSecurityLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addComponent(btnSecurityAdminLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnSecurityUserLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSecurityUserLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecurityUserLoginActionPerformed
        // TODO add your handling code here:
        new UserLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSecurityUserLoginActionPerformed

    public void infoMessage(String message,String title)
    {
        JOptionPane.showMessageDialog(null, message, title, JOptionPane.INFORMATION_MESSAGE);
    }
    
    private void btnSecurityLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecurityLoginActionPerformed
        // TODO add your handling code here:
        String username=txtSecurityID.getText();
        String password=pfSecurityPassword.getText();
        
        try{
            MongoClient mongo = new MongoClient( "localhost" , 27017 ); 
             MongoDatabase db = mongo.getDatabase("RESIDEM");
//             db.createCollection("SecurityDB");
             System.out.println("Collection created");
             MongoCollection<Document> SecurityDB = db.getCollection("SecurityDB");
            // Validating result in mongodb
    //        Document result = AdminDB.find(new BasicDBObject("username", username), new BasicDBObject("password", password));
           FindIterable<Document> iterable =  SecurityDB.find(and ( Filters.eq("username", username)  , Filters.eq("password", password) ) );
           MongoCursor<Document> cursor = iterable.iterator();
           if(cursor.hasNext()){
                System.out.println("User has logged in");
                
               infoMessage("Welcome " + username , "Login Successful!");
                  new Security().setVisible(true);
        this.dispose();
            mongo.close();

           }
           else{
               System.out.print("user login unsuccesful");
               infoMessage("Incorrect Credentials!", "Error");
           }
       }
        catch(Exception e){
            
           System.out.print(e);
            
        }
       
        
    }//GEN-LAST:event_btnSecurityLoginActionPerformed

    private void btnSecurityAdminLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecurityAdminLoginActionPerformed
        // TODO add your handling code here:
        new AdminLogin().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSecurityAdminLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SecurityLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SecurityLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SecurityLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SecurityLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SecurityLogin().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSecurityAdminLogin;
    private javax.swing.JButton btnSecurityLogin;
    private javax.swing.JButton btnSecurityUserLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblSecurityID;
    private javax.swing.JLabel lblSecurityPassword;
    private javax.swing.JPasswordField pfSecurityPassword;
    private javax.swing.JTextField txtSecurityID;
    // End of variables declaration//GEN-END:variables

}
